---
- name: Make sure we have debs directory
  become: true
  file:
    path: ~/debs/
    state: directory
- name: download plex
  become: true
  get_url:
    url: https://downloads.plex.tv/plex-media-server/1.9.6.4429-23901a099/plexmediaserver_1.9.6.4429-23901a099_amd64.deb
    dest: ~/debs/plex.deb
- name: install plex
  become: true
  apt:
    deb: ~/debs/plex.deb
